server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      ####读取分支
      label: master
      server:
        git:
          uri: https://github.com/Tituo09/springcloud-config.git
          search-paths:
            - springcloud-config



eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cloud-config-center3344
    prefer-ip-address: true

#rabbitmq相关配置
rabbitmq:
  host: 62.234.72.166
  port: 5672
  username: guest
  password: guest



##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

